apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: python_copier_template
  title: Python Copier Template
  description: Create a project based on this template using Copier
  tags:
    - recommended
    - techdocs
    - mkdocs
spec:
  owner: kqd14687
  type: documentation

  parameters:
    - title: About You
      required:
        - full_name
        - email
        - owner
      properties:
        full_name:
          title: Firstname LastName
          type: string
        email:
          title: email@diamond.ac.uk
          type: string
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
              - User
    - title: Project Details
      required:
        - repoUrl
        - description
        - owner
      properties:
        repoUrl:
          title: Repository Name and Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            requestUserCredentials:
              secretsKey: USER_OAUTH_TOKEN
              additionalScopes:
                github:
                  - workflow
            allowedHosts:
              - github.com
        description:
          title: Description
          type: string
          description: A short description of your project
    - title: Template Options
      properties:
        docker:
          title: Publish Docker container?
          description: |
            Would you like to publish your project in a Docker container?
            You should select this if you are making a service.
          type: boolean
          default: false
        docs:
          title: Documentation
          description: |
            How would you like to document your project?
            You can start with just a README and change your answer to add a sphinx project later.
          type: string
          default: README
          enum:
            - README
            - sphinx
        typeChecker:
          title: Type Checker
          description: |
            What type checker would you like to use?
            Pyright is recommended for new projects, but it is stricter,
            so you might need to select mypy for existing projects.
          type: string
          default: pyright
          enum:
            - pyright
            - mypy
        pypi:
          title: PyPI?
          description: Would you like the wheel and source distribution to be automatically uploaded to PyPI when a release is made?
          type: boolean
          default: false

  # This template is meant to be used on top of an existing template.
  # By adding the following and fetching from an absolute URL you can
  # add in the docs template
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:copier
      input:
        url: https://github.com/DiamondLightSource/python-copier-template
        values:
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          # These are answers for the copier template
          package_name: ${{ parameters.repoUrl | parseRepoUrl | pick('repo') | replace('-', '_') }}
          description: ${{ parameters.description }}
          git_platform: ${{ parameters.repoUrl | parseRepoUrl | pick('host') }}
          github_org: ${{ parameters.repoUrl | parseRepoUrl | pick('owner') }}
          repo_name: ${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}
          distribution_name: ${{ parameters.repoUrl | parseRepoUrl | pick('repo') }}
          author_name: ${{ parameters.full_name }}
          author_email: ${{ parameters.email }}
          component_owner: ${{ parameters.owner }}
          docker: ${{ parameters.docker }}
          docs_type: ${{ parameters.docs }}
          type_checker: ${{ parameters.typeChecker }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}
        repoVisibility: public
        token: ${{ secrets.USER_OAUTH_TOKEN }}

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
