apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: python_copier_template_2
  title: Python Copier Template 2
  description: Create a project based on this template using Copier
  tags:
    - recommended
    - techdocs
    - mkdocs
spec:
  owner: kqd14687
  type: documentation

  parameters:
    - title: About You
      required:
        - full_name
        - email
        - owner
      properties:
        full_name:
          title: Firstname LastName
          type: string
        email:
          title: email@diamond.ac.uk
          type: string
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Project Details
      required:
        - name
        - description
        - repoUrl
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: A description for the component
        repoUrl:
          title: Repo Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
    - title: Template Options
      properties:
        docker_containers:
          title: Are you working with Docker containers?
          type: boolean
        vscode_option:
          title: Are you using vscode?
          type: boolean
        docs_option:
          title: Would you like docs?
          type: boolean


  # This template is meant to be used on top of an existing template.
  # By adding the following and fetching from an absolute URL you can
  # add in the docs template
  steps:
    - id: fetch
      name: Template Docs Skeleton
      action: fetch:copier
      input:
        url: ./template
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          owner: ${{ parameters.owner }}
          # package_name: ${{ parameters.package_name }}
          # git_platform: ${{ parameters.git_platform }}
          # github_org: ${{ parameters.github_org }}
          # repo_name: ${{ parameters.repo_name }}
          # pypi_name: ${{ parameters.pypi_name }}
          project_description: ${{ parameters.description }}
          full_name: ${{ parameters.full_name }}
          email: ${{ parameters.email }}
          docker_containers: ${{ parameters.docker_containers }}
          vscode_option: ${{ parameters.vscode_option }}
          docs_option: ${{ parameters.docs_option }}
          # repo_url: https://github.com/${{ parameters.github_org }}/${{ parameters.repo_name }}
          # docs_url: https://${{ parameters.github_org }}.github.io/${{ parameters.repo_name }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
