name: CI

on:
  push:
  pull_request:

jobs:
  check:
    uses: ./.github/workflows/_check.yml

  test:
    needs: check
    if: needs.check.outputs.not-in-pr
    uses: ./.github/workflows/_tox.yml
    with:
      tox: pre-commit,pytest

  docs:
    needs: check
    if: needs.check.outputs.not-in-pr
    uses: ./.github/workflows/_docs.yml

  release:
    if: github.ref_type == 'tag'
    needs: docs
    uses: ./.github/workflows/_release.yml
    permissions:
      contents: write
